env:
  browser: true
  es6: true
  node: true
extends:
  - eslint:recommended
  - google
ignorePatterns:
  - lib/meta.js  # eslint doesn’t support import.meta yet
parserOptions:
  ecmaVersion: 2020
  sourceType: module
rules:
  arrow-parens:
    - error
    - as-needed
    - requireForBlockBody: true
  max-len:
    - error
    - code: 120
  object-curly-spacing:
    - error
    - always
    - objectsInObjects: false
